<a href="https://colab.research.google.com/github/Avipsa-Bhujabal/AI_ML_DS_SummerTrainig_2023/blob/main/Summer_Internship_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.22.4'

In [5]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64
(5,)


In [7]:
print(arr[1])
print(arr[-1])
print(arr[1:3])

2
5
[2 3]


In [9]:
arr=np.array([1,2,3,4,5.5,True])
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)

[1.  2.  3.  4.  5.5 1. ]
<class 'numpy.ndarray'>
float64
(6,)


In [10]:
arr=np.array([1,2,3,4,5,True,"anoj"])
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)

['1' '2' '3' '4' '5' 'True' 'anoj']
<class 'numpy.ndarray'>
<U21
(7,)


In [13]:
arr = np.array([1,2,3,4], ndmin=4)
print(arr)
print(np.mean(arr))
print(np.min(arr))
print(np.std(arr))
print(np.sum(arr))

[[[[1 2 3 4]]]]
2.5
1
1.118033988749895
10


In [17]:
arr = np.array(([1,2,3,4],[5,6,7,8]))
print(arr[1][3])
print(arr.ndim)
print(arr.size)

8
2
8


In [21]:
print(np.zeros((2,4)))
print(np.ones((3,4)))
print(np.identity(4))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [22]:
arr=np.random.rand(10,4)
print(arr)

[[0.38978399 0.52554866 0.24598425 0.8735399 ]
 [0.97155403 0.39774431 0.81632266 0.11383164]
 [0.7916436  0.41080417 0.41499218 0.69113343]
 [0.27015351 0.47630381 0.05606018 0.45700448]
 [0.4880996  0.53212111 0.62349684 0.65880208]
 [0.00904133 0.99701455 0.26867511 0.86762817]
 [0.65018739 0.1037336  0.3735843  0.94889221]
 [0.34124484 0.75962854 0.13070651 0.72733296]
 [0.95113484 0.96359453 0.49603495 0.09526193]
 [0.40274688 0.40681412 0.67614328 0.79919366]]


In [24]:
print(np.max(arr),np.min(arr))
arr=np.random.randn(10,5)
print(arr)

0.9884334288229094 0.02639407320930509
[[-0.20373445  0.32464301 -0.94300071  0.82823807  1.5543534 ]
 [-0.25776991 -0.87253759 -0.29051297  0.89214816 -0.19711103]
 [-0.03579027 -0.63731171  0.23300416  1.92173128 -0.78354474]
 [ 0.20075012 -0.34761774  0.82325085  1.99922034 -0.29366438]
 [ 0.20906543  0.49383791 -0.05933097 -0.77069871  0.5290959 ]
 [-0.27652997  1.21221092 -1.78558374 -0.50300222 -0.15273062]
 [-0.72926315 -0.19600122  0.71645103  1.51856572  0.83798604]
 [-0.84593919  1.23317254 -1.06199553  1.5076164  -0.37077295]
 [ 0.07582895  1.20157474  0.95087625 -0.48228982 -1.98574507]
 [ 0.70073184  0.75455803 -0.57743297  1.3655034   0.22560031]]
